### ISSUE TITLE
URGENT - Deprecated Models 04/01/2024 - breaks plugin

### ISSUE THREAD

**Issue by brybalicious** [KellanM/OpenAI-Api-Unreal#66]
As of 04/01/2024, many models have been deprecated as per [Deprecations](https://platform.openai.com/docs/deprecations)

This plugin therefore needs a spring-cleaning to cull deprecated models and add their replacements.

**Comment by brybalicious** [comment]
Specifically, the models used for CallCompletions served via the completions endpoint - https://platform.openai.com/docs/deprecations/instructgpt-models need updating to the gpt-3.5-turbo-instruct endpoint.

Source/OpenAIAPI/Public/OpenAIDefinitions.h

**Comment by brybalicious** [comment]
Guide for updating to new completions model - https://openai.com/blog/gpt-4-api-general-availability

**Comment by brybalicious** [comment]
Build Error for 5.3 with the latest version in Git. Have you tried rebuilding the latest version @KellanM ?

```
Path to .uplugin to rebuild: "D:\OpenAI-Api-Unreal\OpenAIAPI.uplugin"
Folder name for the rebuilt plugin: OpenAIAPI
Running AutomationTool...
Using bundled DotNet SDK version: 6.0.302
Starting AutomationTool...
Parsing command line: BuildPlugin -plugin=D:\Git\OpenAI-Api-Unreal\OpenAIAPI.uplugin -TargetPlatforms=Win64 -package=D:\Unreal\RebuiltPlugins\OpenAIAPI
Initializing script modules...
Total script module initialization time: 0.12 s.
Executing commands...
Copying 51 file(s) using max 64 thread(s)
Reading plugin from D:\Unreal\RebuiltPlugins\OpenAIAPI\HostProject\Plugins\OpenAIAPI\OpenAIAPI.uplugin...
Building plugin for host platforms: Win64
Running: C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\ThirdParty\DotNet\6.0.302\windows\dotnet.exe "C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" UnrealEditor Win64 Development -Project="D:\Unreal\RebuiltPlugins\OpenAIAPI\HostProject\HostProject.uproject" -plugin="D:\Unreal\RebuiltPlugins\OpenAIAPI\HostProject\Plugins\OpenAIAPI\OpenAIAPI.uplugin" -noubtmakefiles -manifest="D:\Unreal\RebuiltPlugins\OpenAIAPI\HostProject\Saved\Manifest-UnrealEditor-Win64-Development.xml" -nohotreload -log="C:\Users\username\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-UnrealEditor-Win64-Development.txt"
Log file: C:\Users\username\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-UnrealEditor-Win64-Development.txt
**Module 'Http' (referenced via Target -> OpenAIAPI.Build.cs) has incorrect text case. Did you mean 'HTTP'?**
Total execution time: 1.51 seconds
**Unhandled exception: System.ArgumentNullException: Value cannot be null. (Parameter 'element')**
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element)
   at UnrealBuildTool.ModuleRules.IsValidForTarget(Type ModuleType, ReadOnlyTargetRules TargetRules, String& InvalidReason) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\ModuleRules.cs:line 1623
   at UnrealBuildTool.UEBuildTarget.AddAllValidModulesToTarget(ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 3886
   at UnrealBuildTool.UEBuildTarget.PreBuildSetup(ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 3354
   at UnrealBuildTool.UEBuildTarget.Create(TargetDescriptor Descriptor, Boolean bSkipRulesCompile, Boolean bForceRulesCompile, Boolean bUsePrecompiled, UnrealIntermediateEnvironment IntermediateEnvironment, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 1366
   at UnrealBuildTool.BuildMode.CreateMakefileAsync(BuildConfiguration BuildConfiguration, TargetDescriptor TargetDescriptor, ISourceFileWorkingSet WorkingSet, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 1114
   at UnrealBuildTool.BuildMode.BuildAsync(List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference WriteOutdatedActionsFile, ILogger Logger, Boolean bSkipPreBuildTargets) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 396
   at UnrealBuildTool.BuildMode.ExecuteAsync(CommandLineArguments Arguments, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 252
   at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 659
Took 1.59s to run dotnet.exe, ExitCode=6
UnrealBuildTool failed. See log for more details. (C:\Users\rainshadow\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-UnrealEditor-Win64-Development.txt)
AutomationTool executed for 0h 0m 1s
AutomationTool exiting with ExitCode=6 (6)
BUILD FAILED

[process exited with code 6 (0x00000006)]
```

**Comment by zhalice2011** [comment]
> Build Error for 5.3 with the latest version in Git. Have you tried rebuilding the latest version @KellanM ?使用 Git 中最新版本的 5.3 生成错误。您是否尝试过重建最新版本？
> 
> ```
> Path to .uplugin to rebuild: "D:\OpenAI-Api-Unreal\OpenAIAPI.uplugin"
> Folder name for the rebuilt plugin: OpenAIAPI
> Running AutomationTool...
> Using bundled DotNet SDK version: 6.0.302
> Starting AutomationTool...
> Parsing command line: BuildPlugin -plugin=D:\Git\OpenAI-Api-Unreal\OpenAIAPI.uplugin -TargetPlatforms=Win64 -package=D:\Unreal\RebuiltPlugins\OpenAIAPI
> Initializing script modules...
> Total script module initialization time: 0.12 s.
> Executing commands...
> Copying 51 file(s) using max 64 thread(s)
> Reading plugin from D:\Unreal\RebuiltPlugins\OpenAIAPI\HostProject\Plugins\OpenAIAPI\OpenAIAPI.uplugin...
> Building plugin for host platforms: Win64
> Running: C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\ThirdParty\DotNet\6.0.302\windows\dotnet.exe "C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" UnrealEditor Win64 Development -Project="D:\Unreal\RebuiltPlugins\OpenAIAPI\HostProject\HostProject.uproject" -plugin="D:\Unreal\RebuiltPlugins\OpenAIAPI\HostProject\Plugins\OpenAIAPI\OpenAIAPI.uplugin" -noubtmakefiles -manifest="D:\Unreal\RebuiltPlugins\OpenAIAPI\HostProject\Saved\Manifest-UnrealEditor-Win64-Development.xml" -nohotreload -log="C:\Users\username\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-UnrealEditor-Win64-Development.txt"
> Log file: C:\Users\username\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-UnrealEditor-Win64-Development.txt
> **Module 'Http' (referenced via Target -> OpenAIAPI.Build.cs) has incorrect text case. Did you mean 'HTTP'?**
> Total execution time: 1.51 seconds
> **Unhandled exception: System.ArgumentNullException: Value cannot be null. (Parameter 'element')**
>    at System.Attribute.GetCustomAttributes(MemberInfo element, Type attributeType, Boolean inherit)
>    at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element)
>    at UnrealBuildTool.ModuleRules.IsValidForTarget(Type ModuleType, ReadOnlyTargetRules TargetRules, String& InvalidReason) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\ModuleRules.cs:line 1623
>    at UnrealBuildTool.UEBuildTarget.AddAllValidModulesToTarget(ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 3886
>    at UnrealBuildTool.UEBuildTarget.PreBuildSetup(ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 3354
>    at UnrealBuildTool.UEBuildTarget.Create(TargetDescriptor Descriptor, Boolean bSkipRulesCompile, Boolean bForceRulesCompile, Boolean bUsePrecompiled, UnrealIntermediateEnvironment IntermediateEnvironment, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 1366
>    at UnrealBuildTool.BuildMode.CreateMakefileAsync(BuildConfiguration BuildConfiguration, TargetDescriptor TargetDescriptor, ISourceFileWorkingSet WorkingSet, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 1114
>    at UnrealBuildTool.BuildMode.BuildAsync(List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference WriteOutdatedActionsFile, ILogger Logger, Boolean bSkipPreBuildTargets) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 396
>    at UnrealBuildTool.BuildMode.ExecuteAsync(CommandLineArguments Arguments, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 252
>    at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 659
> Took 1.59s to run dotnet.exe, ExitCode=6
> UnrealBuildTool failed. See log for more details. (C:\Users\rainshadow\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-UnrealEditor-Win64-Development.txt)
> AutomationTool executed for 0h 0m 1s
> AutomationTool exiting with ExitCode=6 (6)
> BUILD FAILED
> 
> [process exited with code 6 (0x00000006)]
> ```

I have same problem
